### ISSUE TITLE
Training of Autoencoder 

### ISSUE THREAD

**Issue by Ananwang2002** [zoomin-lee/SemCity#2]
Hi! I am very interested in your work and would like to ask how many epochs you trained the autoencoder to achieve the results mentioned in the paper.

I notice that the default in _scripts/train_ae.py_ is **30000 epochs**.

**Comment by zoomin-lee** [comment]
We trained our auto-encoder for **20 epochs** on semantickitti :)

**Comment by Ananwang2002** [comment]
I will give it a try, thx.
