### ISSUE TITLE
Dimension mismatch in loading of diffusion model

### ISSUE THREAD

**Issue by Ananwang2002** [zoomin-lee/SemCity#3]
Hi! I encountered a dimension mismatch when I finished the training of diffusion model and got best model _ema_0.9999_050000.pt_ after 100 diffusion steps.
Once I run the generation script `python sampling/generation.py --num_samples 10 --save_path exp/gen --dataset kitti `, there was an error of dimension mismatch between ckpt model and new defined model. Note that I have not changed any default set of args in `parser_util.py` and `scripts_utils.py`
```
   model.load_state_dict(torch.load(DIFF_PATH, map_location="cpu"))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TriplaneUNetModel:
        size mismatch for in_conv.0.conv_xy.weight: copying a param with shape torch.Size([64, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 16, 1, 1]).
        size mismatch for in_conv.0.conv_xz.weight: copying a param with shape torch.Size([64, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 16, 1, 1]).
        size mismatch for in_conv.0.conv_yz.weight: copying a param with shape torch.Size([64, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 16, 1, 1])
```

**Comment by nautilus-a** [comment]
We appreciate your interest in our work.
After the issue, we checked and ran our code, but we couldn't reproduce the error. The error message shows a twofold difference in size between the model weights and the model architecture. From this, we guess that the SSC refinements option is turned on. Could you check if the option is False?

**Comment by Ananwang2002** [comment]
Actually, I find that the command you give `python scripts/train_diffusion_main.py --ssc_refine False --triplane_loss_type l2 --save_path exp/diff` for training diffusion model open the SSC refinements option while I do not want this happen, and after removing this option `python scripts/train_diffusion_main.py --triplane_loss_type l2 --save_path exp/diff`  the dimension will be 16.

**Comment by bian-hengwei** [comment]
> Actually, I find that the command `python scripts/train_diffusion_main.py --ssc_refine False --triplane_loss_type l2 --save_path exp/diff` you give for training diffusion model open the SSC refinements option while I do not want to happen, and after removing this option `python scripts/train_diffusion_main.py --triplane_loss_type l2 --save_path exp/diff` the dimension will be 16. Could you please check it out again?

I encountered the same error when training diffusion with option `--ssc_refine False`. Ignoring the option worked. According to argparse documentation, "The bool() function is not recommended as a type converter. All it does is convert empty strings to False and non-empty strings to True. This is usually not what is desired." [Link](https://docs.python.org/3/library/argparse.html).

**Comment by nautilus-a** [comment]
We are sorry for the inconvenience. We found an option error caused during refactoring. We have updated the codes and README.
If the error is not resolved, please let us know.
Thanks
