### ISSUE TITLE
Did you reproduce the scpnet results?

### ISSUE THREAD

**Issue by lcl124252** [zoomin-lee/SemCity#4]
I noticed in your paper that there are examples of scpnet in combination. Have you reproduced the results of the scpnet paper? I remember that the scpnet paper authors did not give all the code, if you have reproduced it can you share your reproduced code?

**Comment by zoomin-lee** [comment]
We didn't reproduce the scpent. We used the official model weights from the scpnet repo.

**Comment by lcl124252** [comment]
> We didn't reproduce the scpent. We used the official model weights from the scpnet repo.

I see. Thank you for your answer.

**Comment by t-martyniuk** [comment]
@zoomin-lee could you please share the model checkpoint you used? it's currently unavailable in the SCPNet repo.
