### ISSUE TITLE
Visualization tools

### ISSUE THREAD

**Issue by bian-hengwei** [zoomin-lee/SemCity#5]
Hi! Thank you for open-sourcing your incredible work. I wonder if you could also share your visualization tools for generated .label files?

**Comment by zxczrx123** [comment]
+1

**Comment by zxczrx123** [comment]
I have writed a simple visualization code. @bian-hengwei 
```python
import numpy as np
import pyrender
import trimesh

semantic_kitti_colors = {
    0: [0, 0, 0],       
    10: [245, 150, 100],
    20: [245, 230, 100],
    40: [150, 60, 30],  
    44: [180, 30, 80],  
    48: [255, 0, 0],    
    50: [30, 30, 255],  
    51: [90, 30, 150],  
    70: [250, 80, 100], 
    71: [110, 190, 160],
    72: [255, 0, 255],  
    80: [255, 255, 50], 
    81: [200, 200, 200] 
}

original_shape = (256, 256, 32)

filename = 'exp/gen/sample/0.label'
sample = np.fromfile(filename, dtype=np.uint16)

print("Sample shape:", sample.shape)

voxel_map = sample.reshape(original_shape)

scene = pyrender.Scene()
voxels = voxel_map > 0
occupied_voxels = np.argwhere(voxels)

colors = np.array([semantic_kitti_colors[label] for label in voxel_map[voxels]])

point_cloud_with_colors = trimesh.points.PointCloud(occupied_voxels, colors=colors)

cloud_with_colors = pyrender.Mesh.from_points(point_cloud_with_colors.vertices, colors=point_cloud_with_colors.colors)

scene = pyrender.Scene()
scene.add(cloud_with_colors)

pyrender.Viewer(scene, use_raymond_lighting=True)
```
![image](https://github.com/zoomin-lee/SemCity/assets/37107333/2b528e33-abc6-45f5-90a3-5a72dfb2d8b9)

**Comment by bian-hengwei** [comment]
> I have writed a simple visualization code. @bian-hengwei
> 
> ```python
> import numpy as np
> import pyrender
> import trimesh
> 
> semantic_kitti_colors = {
>     0: [0, 0, 0],       
>     10: [245, 150, 100],
>     20: [245, 230, 100],
>     40: [150, 60, 30],  
>     44: [180, 30, 80],  
>     48: [255, 0, 0],    
>     50: [30, 30, 255],  
>     51: [90, 30, 150],  
>     70: [250, 80, 100], 
>     71: [110, 190, 160],
>     72: [255, 0, 255],  
>     80: [255, 255, 50], 
>     81: [200, 200, 200] 
> }
> 
> original_shape = (256, 256, 32)
> 
> filename = 'exp/gen/sample/0.label'
> sample = np.fromfile(filename, dtype=np.uint16)
> 
> print("Sample shape:", sample.shape)
> 
> voxel_map = sample.reshape(original_shape)
> 
> scene = pyrender.Scene()
> voxels = voxel_map > 0
> occupied_voxels = np.argwhere(voxels)
> 
> colors = np.array([semantic_kitti_colors[label] for label in voxel_map[voxels]])
> 
> point_cloud_with_colors = trimesh.points.PointCloud(occupied_voxels, colors=colors)
> 
> cloud_with_colors = pyrender.Mesh.from_points(point_cloud_with_colors.vertices, colors=point_cloud_with_colors.colors)
> 
> scene = pyrender.Scene()
> scene.add(cloud_with_colors)
> 
> pyrender.Viewer(scene, use_raymond_lighting=True)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/37107333/315885737-2b528e33-abc6-45f5-90a3-5a72dfb2d8b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODI5NjksIm5iZiI6MTcxMTA4MjY2OSwicGF0aCI6Ii8zNzEwNzMzMy8zMTU4ODU3MzctMmI1MjhlMzMtYWJjNi00NWY1LTkwYTMtNWE3MmRmYjJkOGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0NDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NTVjYTYxNWUzYTlmN2I4ZDU0YzYyNTEwZTBjZTlhNjg5ZTViYmQxYTQ3ZGY1YTJkMzdjZjgzMThkZTcyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wB-Lv0mpzJYanjYEyOJN8bqmB4c1dPSblZ4m5DRKxaA)

Thanks for sharing!

**Comment by zoomin-lee** [comment]
Thank you all. We also use 'flags=RenderFlags.SHADOWS_ALL' for shadows :)
